name: Duplicate Issue Detector

on:
  issues:
    types: [opened, edited]

jobs:
  detect-duplicate:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      contents: read
    steps:
      - name: Validate Similar Issues
        uses: actions-cool/issues-similarity-analysis@v1.3.2
        with:
          filter-threshold: 0.5
          title-excludes: 'bug, feature, question'
          comment-title: '### Similar issues found'
          comment-body: '${index}. [${title}](${url})'
